### ISSUE TITLE
不支持迁移unlogged分片表

### ISSUE THREAD

**Issue by ChenHuajun** [cloud-sn2/cigration#4]
## 问题
迁移unlogged分片表，在启动迁移任务时会失败

## 原因
cigration利用逻辑复杂做分片迁移。unlogged表不产生WAL，所以创建包含unlogged的逻辑订阅时PG会报错。

## 对策
- 用户
  1. 把unlogged表改成普通的logged表
  2. 把unlogged表临时删掉，迁移作业完成后再加回来
- cigration改进
  1. 生成迁移任务时忽视和普通表无亲和约束的unlogged表
  2. 如果存在亲和约束，生成任务时提前报错

**Comment by cloud-sn2** [comment]
cigration改进部分已完成
