### ISSUE TITLE
不支持迁移无主键的分片表

### ISSUE THREAD

**Issue by ChenHuajun** [cloud-sn2/cigration#5]
## 问题
不支持迁移无主键的分片表。启动迁移任务后，任务会失败。
```
postgres=# select error_message from cigration.pg_citus_shard_migration where status='error';
                            error_message
----------------------------------------------------------------------
 it does not has a replica identity or it does not has a primary key.
(1 row)
```

## 原因
对于无主键的分片表，开启逻辑订阅后，PG会阻止表的更新的删除。考虑到着可能会影响到生产业务，cigration对这种情况会进行检查并提前报错。

## 改进
可能有些表难以创建主键，但是用户可以容忍迁移分片期间不更新表。为支持这类场景，`cigration_start_shard_migration_task()`已经提供了`ignore_replica_identity_check`参数控制。

为了增强易用性，准备进行以下修改
1. 将`replica_identity`检查提前到生成迁移作业时，如果不存在主键输出告警
2. `ignore_replica_identity_check`参数改名为`with_replica_identity_check`，默认值为false
3. 在`cigration_batch_run_migration_tasks()`中增加`with_replica_identity_check`参数

**Comment by datager** [comment]
无主键的表, 可以设置replicaIdentity=FULL, 这样可以吗

**Comment by ChenHuajun** [comment]
这个问题这几天会fix

**Comment by cloud-sn2** [comment]
> 无主键的表, 可以设置replicaIdentity=FULL, 这样可以吗
可以设置replica Identity 为full或唯一索引。

现在已修改为不强制要求有主键或`replica_identity`，具体参考readme.md
