### ISSUE TITLE
无法继续使用create_distributed_table()

### ISSUE THREAD

**Issue by ChenHuajun** [cloud-sn2/cigration#6]
## 问题
安装cigration插件后，无法继续使用`create_distributed_table()`创建分片表

## 原因
Citus的分片表存在亲和关系，互相亲和的一组表必须同时迁移，否则亲和关系将会被破坏导致业务SQL异常。
为了防止生成分片迁移任务后又创建新的分片表和原来的表亲和导致亲和关系和数据分布不一致，cigration禁用了Citus原始的`create_distributed_table()`，取而代之的是`cigration_create_distributed_table()`。`cigration_create_distributed_table()`会提前对亲和关系进行判断并报错。

## 改进
上面防范方式比较粗暴，影响了Citus的使用接口，而且也不能完全避免亲和关系被破坏（当前仅禁止了2参方式调用`create_distributed_table()`；并且也不能阻止`mark_tables_colocated()`和`update_distributed_table_colocation()`）。

但是目前也没有更好的手段进行防范（Citus通过内部函数而不是SQL更新元数据表，所以在`pg_dist_partition`表上创建触发器的做法行不通）。

因此，保留目前的防范手段，并且对`cigration_create_distributed_table()`进行增强，是其在功能上可以完全替代`create_distributed_table()`，比如支持`colocate_with=>'default'`。

**Comment by cloud-sn2** [comment]
已经改进。cigration_create_distributed_table()完全和原Citus的create_distributed_table()的接口兼容。并且已完善文档。
